### ISSUE TITLE
Press CTRL or SHIFT on boot

### ISSUE THREAD

**Issue by rderooy** [oksoelsha/openmsx-launcher#3]
feature request.

As you know sometimes you have a piece of MSX software that requires you to press CTRL or SHIFT on boot to disable the second FDD, or disable the FDD completely. So how about adding some option to the software settings to accomplish this? When starting openmsx, all you need to do is launch one of the attached scripts (remove the .txt extension, that I had to add to satisfy github).

[pressctrl.tcl.txt](https://github.com/oksoelsha/openmsx-launcher/files/391792/pressctrl.tcl.txt)
[pressshift.tcl.txt](https://github.com/oksoelsha/openmsx-launcher/files/391793/pressshift.tcl.txt)

Note: do not throw the TCL files into your openmsx/scripts directory or they will be run on EVERY boot.

**Comment by oksoelsha** [comment]
That's a indeed a very good feature to add. I hacked something together and I got it to work with some disks that require pressing Ctrl key while booting. I am thinking of adding this option to the Add/Edit game window under the Disk tab (the option is called FDD Mode and the three dropdown values are Enable Both, Disable Second and Disable Both). The two scripts will be placed in the same folder where the extra-data and README files are.

Would you be interested in testing a new Dev build? It'll just be the openmsx-launcher jar and I think I'll have one ready in a week or two.

**Comment by rderooy** [comment]
Yes I can test a dev build. Just be aware that in two weeks I will be on vacation :-)

**Comment by oksoelsha** [comment]
[openmsx-launcher.zip](https://github.com/oksoelsha/openmsx-launcher/files/403079/openmsx-launcher.zip)

Here's a build that contains the implementation as I described it above. Here's what you need to do:
- Backup openmsx-launcher.jar in the lib/ folder of the launcher (by removing it completely out of that folder)
- Backup the databases folder in your user home folder by making a copy of it (the reason for this is because the new implementation alters the schema slightly)
- Place the attached jar file in the lib/ folder
- Place your two scripts in the launcher folder (where the files extra-data.dat and README.html files are)

Now try it and let me know.

**Comment by rderooy** [comment]
I installed, the new jar file, and can see the options, but when I enable either disable second, or disable all, I can no longer start the MSX.

I tried this with the _msx2plus machine type (FS-A1WSX), and the MSX BASIC KUN Plus v2.1 ROM, as it is just a MSX-BASIC compiler, so it boots to BASIC and lets me try stuff.
The moment I change the setting back to 'Enable Both Drives', I can start it again.

Starting it myself with shift pressed has the desired effect of disabling the FDD.

**Comment by oksoelsha** [comment]
When I tried it with a Boosted MSX2 machine and the 'Disable Both' option, I can see the machine boot up with no disk drives, and I tried all that on my Ubuntu and Windows machines.

Did you place your scripts without the txt extension?

It seems that I will have to give you a build that does some logging to see what command line switches the launcher outputs. It is as if openmsx doesn't find the scripts and that's why if fails to start.

**Comment by rderooy** [comment]
Sorry, your right. I skipped that. I added them into the app directory and now when I select to disable one or both, I can start the emulator unlike before.

Having said that, in my testing I noticed the option does not work with all machine types. It works with the TurboR (GT), but not with the msx2plus for some reason... I will try to have a look at it this evening if I can.

**Comment by oksoelsha** [comment]
I had the same problem: the pressctrl script didn't work on MSX2+ but worked on MSX2_Boosted and Turbo-R. I took a look at the script and did two things:
- Simplified it by removing the procedure and just made it one line (that is more of a clean up and as expected didn't fix the problem)
- Extended the time the Ctrl key pressed from 6 to 9 seconds.

The final version of the script became:

after boot { keymatrixdown 6 2; after time 9 "keymatrixup 6 2"}

and that worked on the three machines I tried it on.

**Comment by oksoelsha** [comment]
I ended up setting the duration for pressing the Ctrl key to 14 to accommodate the longest boot time for all machines. The feature is part of the current build and will be in the next 1.8 release.

Thanks for the suggestion and testing. I will add your name to the credits section in the About window.

**Comment by rderooy** [comment]
Thanks for adding the feature! You really did most of the work, I did
hardly more then give the suggestion.
